version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analise-questoes-api
    ports:
      - "3000:3000"
    environment:
    
    volumes:
      # Volume para persistir imagens e respostas
      - ./uploads:/app/uploads
      - ./responses:/app/responses
    restart: unless-stopped
    # Verificação de saúde para garantir que o serviço está funcionando
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s